### ISSUE TITLE
Task List & Troubleshooting

### ISSUE THREAD

**Issue by Lucas-Paiva** [Lucas-Paiva/Lucas-Paiva#1]
To-do tasks for the next version:

- [ ] Increment layout and refactor the GUI script
- [ ] Add encoding option field
- [ ] Fix the flattered & nested json question
- [ ] Fix the data preview output
